FROM openjdk:8-jre-alpine

COPY ./target/uberjar/wb-es-indexer-standalone.jar /srv/app.jar
COPY ./docker/web-entrypoint.sh /
ENTRYPOINT ["/web-entrypoint.sh"]

EXPOSE 3000

CMD ["java", "-jar", "/srv/app.jar"]
