FROM openjdk:8-jre-alpine

ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY ./target/uberjar/wb-es-web-standalone.jar /srv/app.jar
COPY ./docker/web-entrypoint.sh /
ENTRYPOINT ["/web-entrypoint.sh"]

EXPOSE 3000

CMD ["java", "-server", "-jar", "/srv/app.jar"]

