FROM elasticsearch:2.4.6-alpine

USER root
WORKDIR /usr/share/elasticsearch
RUN bin/plugin install cloud-aws
USER elasticsearch

ADD ./elasticsearch.yml /usr/share/elasticsearch/config
USER root
RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
USER elasticsearch

EXPOSE 9200